### ISSUE TITLE
Signup prompt

### ISSUE THREAD

**Issue by forivall** [DarkThemeHub/GithubDarkTheme#190]
**Describe the bug**
The signup prompt is light

**Expected behavior**
should be dark

**Screenshots**
![Screen Shot 2020-10-28 at 1 18 34 PM](https://user-images.githubusercontent.com/760204/97491941-1b252880-1920-11eb-94cf-20820cb8c0f0.png)

**Proposed Fix**
```css
.signup-prompt-bg {
    background-image: linear-gradient(180deg,hsla(0,0%,0%,0) 50%,#25272a),linear-gradient(70deg,#2f363d, 32%,#24292e);
  }
```
![Screen Shot 2020-10-28 at 1 19 09 PM](https://user-images.githubusercontent.com/760204/97492002-2f692580-1920-11eb-9f7f-232c330a5f5b.png)
