### ISSUE TITLE
background of read notifications is white

### ISSUE THREAD

**Issue by bryangingechen** [DarkThemeHub/GithubDarkTheme#204]
**Describe the bug**
On https://github.com/notifications, the background of a notification which has been read is white.

**Expected behavior**
I expected the background to be dark so that the text is readable.

**Screenshots**
Here's how it currently looks for me:

<img width="1042" alt="Screen Shot 2020-11-18 at 11 07 21 AM" src="https://user-images.githubusercontent.com/5209952/99556020-0243ec00-298f-11eb-8495-6e93b3a32897.png">

If I turn off this rule in the CSS inspector, it looks much better:
<img width="1033" alt="Screen Shot 2020-11-18 at 11 07 32 AM" src="https://user-images.githubusercontent.com/5209952/99556025-02dc8280-298f-11eb-934f-1ab0d2b8e5b2.png">

**If this is a beta feature**
Please paste the html here of the element, including the parent element housing it.

NOTE: beta features are prone to change, and may not be worked on depending how much work is to be done.

**Comment by forivall** [comment]
hotfix:
```css
.notifications-list-item.notification-archived, .notifications-list-item.notification-read {
  background: #1d1d1d !important; }
```
